name: esc_pos_utils
description: Basic Flutter/Dart classes for ESC/POS printing. Ticket class generates ESC/POS commands that can be sent to a thermal printer.
version: 1.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  gbk_codec: ^0.4.0
  image: ^4.2.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/esc_pos_utils/resources/capabilities.json
